name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['net6.0', 'net7.0', 'net8.0', 'net10.0']

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
          10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --framework ${{ matrix.dotnet-version }} src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj
    - name: Test
      run: dotnet test --verbosity normal
