name: Create NuGet and GitHub Release

on:
  pull_request:
    types:
      - closed

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

### TODO: Replace instances of './.github/workflows/' w/ `auth0/dx-sdk-actions/workflows` and append `@latest` after the common `dx-sdk-actions` repo is made public.
### TODO: Also remove `get-prerelease`, `get-release-notes`, `get-version`, `nuget-publish`, `release-create`, and `tag-exists` actions from this repo's .github/actions folder once the repo is public.
### TODO: Also remove `nuget-release` workflow from this repo's .github/workflows folder once the repo is public.

jobs:
  rl-scanner:    
    uses: ./.github/workflows/rl-secure.yml
    with:
      project-path: " "
      artifact-name: "auth0-aspnetcore-authentication.tgz"
    secrets:
      RLSECURE_LICENSE: ${{ secrets.RLSECURE_LICENSE }}
      RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
      SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
      PRODSEC_TOOLS_USER: ${{ secrets.PRODSEC_TOOLS_USER }}
      PRODSEC_TOOLS_TOKEN: ${{ secrets.PRODSEC_TOOLS_TOKEN }}
      PRODSEC_TOOLS_ARN: ${{ secrets.PRODSEC_TOOLS_ARN }}


  release:
    needs: rl-scanner
    uses: ./.github/workflows/nuget-release.yml    
    with:
      dotnet-version: 8.0.x
      project-paths: "['src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj']"
    secrets:
      nuget-token: ${{ secrets.NUGET_APIKEY }}
      github-token: ${{ secrets.GITHUB_TOKEN }}